name: build
on:
  push:
    branches:
      - main

env:
  GENERAL_FLAGS: "-DRETRO_DISABLE_PLUS=ON -DCMAKE_BUILD_TYPE=Release"
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@main
    - uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: gradlew
      working-directory: ./framework/external
      run: ./build_externals_windows.bat
    - name: artifact
      uses: actions/upload-artifact@main
      with:
        name: project
        path: ./Oxygen/sonic3air/build/_android/app/build/outputs/apk
